### ISSUE TITLE
[Feat] Company CRUDS

### ISSUE THREAD

**Issue by lukeydokey** [J1P3ter/Astraphe#1]
## TODO List

- [x] Product Server Module 생성
- [x] Company Entity 생성
- [x] Company CRUD
- [x] Company Search
- [x] Test 코드 작성
