### ISSUE TITLE
[Feat] Common Module 추가

### ISSUE THREAD

**Issue by lukeydokey** [J1P3ter/Astraphe#10]
## TODO List

- [x] Custom Response 작성
- [x] Custom Exception 작성
- [x] Custom Exception Handler 작성
- [x] CorsConfigurer 작성
- [x] CacheConfig 작성

## 참고
- config들이 localhost기준으로 작성 되어 있어서, 동적으로 host 주입할 방법을 알아봐야함
  - @Value annotation 활용해서 해결 완료
