### ISSUE TITLE
[Feat] user-server

### ISSUE THREAD

**Issue by VoiceofSiren** [J1P3ter/Astraphe#2]
## TODO List

- [x] user-server 만들기.
- [x] User Entity 정의하기.
- [x] 회원가입 구현하기.
- [x] 회원가입 테스트 코드 작성하기.
- [x] 로그인 구현하기.
- [x] 로그인 테스트 코드 작성하기.
- [x] 회원 정보 조회하기.
- [x] 회원 정보 조회 테스트 코드 작성하기.
- [x] 회원 정보 수정하기.
- [x] 회원 정보 수정 테스트 코드 작성하기.
- [x] 회원 정보 삭제하기.
- [x] 회원 정보 삭제 테스트 코드 작성하기.
