### ISSUE TITLE
[Feat] Shipping Address

### ISSUE THREAD

**Issue by VoiceofSiren** [J1P3ter/Astraphe#37]
## TODO List

- [x] Gateway의 routing 경로 중에서 /api/shipping-addresses/**를 제거합니다.
- [x] User에 shippingAddress 필드를 추가합니다.
- [x] User Entity에 필드를 추가함에 따라 일부 로직을 수정합니다.
