### ISSUE TITLE
[Feat] 모니터링

### ISSUE THREAD

**Issue by lukeydokey** [J1P3ter/Astraphe#40]
## TODO List

- [x] 각 서버 모니터링 설정 추가
- [x] prometheus.yaml 작성
- [x] grafana 에서 metric 확인
- [x] grafana 슬랙 알림 추가
- [x] 운영 환경에 세팅
