### ISSUE TITLE
[Feat] 관심 상품 등록

### ISSUE THREAD

**Issue by ayboori** [J1P3ter/Astraphe#92]
## TODO List

- [x] subscribeProduct Entity 생성
- [x] subscribeProduct CRD (수정은 필요 없고, 구독 취소 / 재구독 등으로 구현)
- [ ] 구독한 상품의 `startSaleTime` 10분 전 슬랙 알림 발송
